name: Update IHSG Forecast

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * 1-5" # setiap hari kerja jam 02:00 UTC
  workflow_dispatch:

jobs:
  forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }} # <- pastikan ini ada

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install yfinance openpyxl joblib xgboost pandas numpy

      - name: Run forecast script
        run: |
          python update_forecast.py

      - name: Commit and push results
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ihsg_forecast.xlsx
          git commit -m "Update forecast [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/josephines1/prediksi-ihsg-xgboost.git HEAD
